development: &default
  adapter: postgresql
  database: collateral_development
  min_messages: WARNING
  reconnect: true
  pool: 5
  port: 5432

test:
  <<: *default
  database: collateral_test

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: collateral_production
  pool: 5
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
