development: &default
  adapter: postgresql
  database: backbone_data_bootstrap_development
  min_messages: WARNING
  pool: 5
  reconnect: true
  username: postgres
  host: 'db'
  port: 5432

test:
  <<: *default
  database: backbone_data_bootstrap_test
