development: &default
  adapter: postgresql
  database: collateral_dev
  min_messages: WARNING
  pool: 5
  reconnect: true
  username: tjones
  password: passw0rd
  host: localhost
  port: 5432

test:
  <<: *default
  database: collateral_test

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: collateral_production
  pool: 5
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>