development:
  adapter: postgresql
  encoding: unicode
  database: site_development
  pool: 5
  timeout: 5000
#   #host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: site_test
  pool: 5
  timeout: 5000
#   #host: localhost