development: &default
  adapter: postgresql
  database: collateral_dev
  min_messages: WARNING
  pool: 5
  reconnect: true
  host: localhost
  port: 5432

test:
  <<: *default
  database: collateral_test
